export const colors = {
  fg:            "var(--c-fg)",
  bg:            "var(--c-bg)",
  surface:       "var(--c-surface)",
  border:        "var(--c-border)",
  subtle:        "var(--c-subtle)",
  muted:         "var(--c-muted)",
  faint:         "var(--c-faint)",
  dimmed:        "var(--c-dimmed)",
  dark:          "var(--c-dark)",
  secondary:     "var(--c-secondary)",
  success:       "var(--c-success)",
  successBg:     "var(--c-success-bg)",
  danger:        "var(--c-danger)",
  dangerBg:      "var(--c-danger-bg)",
  warningText:   "var(--c-warning-text)",
  warningBg:     "var(--c-warning-bg)",
  warningBorder: "var(--c-warning-border)",
  chipBg:        "var(--c-chip-bg)",
  inputBg:       "var(--c-input-bg)",
  divider:       "var(--c-divider)",
  overlay:       "var(--c-overlay)",
  info:          "var(--c-info)",
  infoBg:        "var(--c-info-bg)",
};

export const radii = {
  sm: 8,
  md: 10,
  lg: 12,
  xl: 16,
  pill: 20,
  round: "50%",
};
